
---------------------------------------------------------------------
-- Builder. Everything above (MAP) is generated by
-- tools/osm_to_babrru.py from the OpenStreetMap export - all geometry is
-- worked out there, so this part just creates the parts.
---------------------------------------------------------------------

local Lighting = game:GetService("Lighting")
local Workspace = game:GetService("Workspace")

-- Look settings - flip off if the game lags.
local NIGHT_MODE = true -- night sky, glow, lit windows and street lamps that light the road

local function safeMaterial(name)
	local ok, material = pcall(function()
		return Enum.Material[name]
	end)
	if ok and material then
		return material
	end
	return Enum.Material.SmoothPlastic
end

local function numbers(s)
	local out = {}
	for value in string.gmatch(s, "%S+") do
		out[#out + 1] = tonumber(value)
	end
	return out
end

local old = Workspace:FindFirstChild("BabrruMap")
if old then
	old:Destroy()
end
local root = Instance.new("Folder")
root.Name = "BabrruMap"
root.Parent = Workspace

local folders = {}
local function folder(name)
	if not folders[name] then
		local f = Instance.new("Folder")
		f.Name = name
		f.Parent = root
		folders[name] = f
	end
	return folders[name]
end

-- Spawn on a real Babrru street, created first so players never spawn
-- before it exists (the rest of the map fills in over a few seconds).
local spawn = Instance.new("SpawnLocation")
spawn.Name = "BabrruSpawn"
spawn.Anchored = true
spawn.CanCollide = false
spawn.Transparency = 1
spawn.Neutral = true
spawn.Duration = 0
spawn.Size = Vector3.new(10, 1, 10)
spawn.CFrame = CFrame.new(MAP.spawn[1], 1, MAP.spawn[2]) * CFrame.Angles(0, math.rad(MAP.spawn[3]), 0)
spawn.Parent = root

local built = 0
local function finish(part, style)
	part.Anchored = true
	part.Color = style.color
	part.Material = style.material
	part.Transparency = style.transparency
	part.Reflectance = style.reflectance
	part.CanCollide = style.collide
	if not style.collide then
		part.CanQuery = false
		part.CanTouch = false
	end
	part.CastShadow = style.shadow
	part.TopSurface = Enum.SurfaceType.Smooth
	part.BottomSurface = Enum.SurfaceType.Smooth
	part.Name = style.name
	part.Parent = style.folder
	built = built + 1
	-- Yield now and then so building ~20k parts never trips Roblox's
	-- "script ran too long" limit.
	if built % 400 == 0 then
		task.wait()
	end
	return part
end

local STYLES = {}
for i, s in ipairs(MAP.styles) do
	local lit = s[11] == 1 -- only glows (Neon) at night
	local material = (lit and NIGHT_MODE) and Enum.Material.Neon or safeMaterial(s[5])
	STYLES[i] = {
		name = s[1],
		color = (lit and not NIGHT_MODE) and Color3.fromRGB(30, 38, 52) or Color3.fromRGB(s[2], s[3], s[4]),
		material = material,
		collide = s[6] == 1,
		transparency = s[7],
		reflectance = s[8],
		shadow = s[9] == 1,
		folder = folder(s[10]),
		building = s[12] == 1,
	}
end
local function styleNamed(name)
	for i, s in ipairs(MAP.styles) do
		if s[1] == name then
			return STYLES[i]
		end
	end
end
local WINDOW_LIT = styleNamed("Window")
local WINDOW_DARK = styleNamed("WindowDark")
local TRUNK = styleNamed("Trunk")
local LEAVES = styleNamed("Leaves")

-- Boxes: roads, markings, buildings, crossings, bus stops...
local FLOOR_HEIGHT = 3 * MAP.scale
local b = numbers(MAP.boxes)
for i = 1, #b, 8 do
	local style = STYLES[b[i]]
	local sx, sy, sz = b[i + 4], b[i + 5], b[i + 6]
	local rotation = CFrame.Angles(0, math.rad(b[i + 7]), 0)
	local p = Instance.new("Part")
	p.Size = Vector3.new(sx, sy, sz)
	p.CFrame = CFrame.new(b[i + 1], b[i + 2], b[i + 3]) * rotation
	finish(p, style)

	-- Buildings get a band of windows on each of their first two floors;
	-- about 60% are lit at night (a fixed pattern, same every time).
	if style.building then
		local floors = math.floor(sy / FLOOR_HEIGHT + 0.5)
		for f = 0, math.min(floors, 2) - 1 do
			local bandY = (f + 0.55) * FLOOR_HEIGHT
			if bandY > sy - 0.5 * MAP.scale then
				break
			end
			local lit = (math.floor(i / 8) * 7 + f * 3) % 10 < 6
			local band = Instance.new("Part")
			band.Size = Vector3.new(sx + 0.12, 1.1 * MAP.scale, sz + 0.12)
			band.CFrame = CFrame.new(b[i + 1], bandY, b[i + 3]) * rotation
			finish(band, lit and WINDOW_LIT or WINDOW_DARK)
		end
	end
end

-- Pitched roofs: two WedgeParts leaning against each other at the ridge.
local roofs = numbers(MAP.roofs)
for i = 1, #roofs, 8 do
	local p = Instance.new("WedgePart")
	p.Size = Vector3.new(roofs[i + 4], roofs[i + 5], roofs[i + 6])
	p.CFrame = CFrame.new(roofs[i + 1], roofs[i + 2], roofs[i + 3]) * CFrame.Angles(0, math.rad(roofs[i + 7]), 0)
	finish(p, STYLES[roofs[i]])
end

-- Wedges: pairs of them make the exact outline of non-rectangular
-- buildings and of lakes/river areas (each pair = one triangle).
local w = numbers(MAP.wedges)
for i = 1, #w, 13 do
	local p = Instance.new("WedgePart")
	p.Size = Vector3.new(w[i + 10], w[i + 11], w[i + 12])
	p.CFrame = CFrame.fromMatrix(
		Vector3.new(w[i + 1], w[i + 2], w[i + 3]),
		Vector3.new(w[i + 4], w[i + 5], w[i + 6]),
		Vector3.new(w[i + 7], w[i + 8], w[i + 9])
	)
	finish(p, STYLES[w[i]])
end

-- Balls: tree tops (each gets a trunk down to the ground).
local balls = numbers(MAP.balls)
for i = 1, #balls, 5 do
	local style = STYLES[balls[i]]
	local x, y, z, d = balls[i + 1], balls[i + 2], balls[i + 3], balls[i + 4]
	local p = Instance.new("Part")
	p.Shape = Enum.PartType.Ball
	p.Size = Vector3.new(d, d, d)
	p.CFrame = CFrame.new(x, y, z)
	finish(p, style)
	if style == LEAVES then
		local trunkHeight = y - d * 0.3
		local trunk = Instance.new("Part")
		trunk.Size = Vector3.new(0.35 * MAP.scale, trunkHeight, 0.35 * MAP.scale)
		trunk.CFrame = CFrame.new(x, trunkHeight / 2, z)
		finish(trunk, TRUNK)
	end
end

-- Street lamps: pole, arm reaching over the road, lamp head. Every second
-- one casts real light - looks the same at night for half the GPU cost.
local POLE = { name = "LampPole", color = Color3.fromRGB(60, 62, 68), material = Enum.Material.Metal, collide = true, transparency = 0, reflectance = 0, shadow = true, folder = folder("StreetLamps") }
local ARM = { name = "LampArm", color = POLE.color, material = Enum.Material.Metal, collide = false, transparency = 0, reflectance = 0, shadow = false, folder = POLE.folder }
local HEAD = { name = "Lamp", color = Color3.fromRGB(255, 226, 160), material = Enum.Material.Neon, collide = false, transparency = 0, reflectance = 0, shadow = false, folder = POLE.folder }
local lampHeight = 8 * MAP.scale
local armLength = 1.4 * MAP.scale
local lamps = numbers(MAP.lamps)
local lampIndex = 0
for i = 1, #lamps, 4 do
	local base = Vector3.new(lamps[i], 0, lamps[i + 1])
	local toward = Vector3.new(lamps[i + 2], 0, lamps[i + 3])
	local pole = Instance.new("Part")
	pole.Size = Vector3.new(0.25 * MAP.scale, lampHeight, 0.25 * MAP.scale)
	pole.CFrame = CFrame.new(base + Vector3.new(0, lampHeight / 2, 0))
	finish(pole, POLE)
	local armCenter = base + toward * (armLength / 2) + Vector3.new(0, lampHeight, 0)
	local arm = Instance.new("Part")
	arm.Size = Vector3.new(0.12 * MAP.scale, 0.12 * MAP.scale, armLength)
	arm.CFrame = CFrame.lookAt(armCenter, armCenter + toward)
	finish(arm, ARM)
	local headPos = base + toward * armLength + Vector3.new(0, lampHeight - 0.2, 0)
	local head = Instance.new("Part")
	head.Size = Vector3.new(0.35 * MAP.scale, 0.15 * MAP.scale, 0.6 * MAP.scale)
	head.CFrame = CFrame.lookAt(headPos, headPos + toward)
	finish(head, HEAD)
	lampIndex = lampIndex + 1
	if NIGHT_MODE and lampIndex % 2 == 0 then
		local light = Instance.new("SpotLight")
		light.Face = Enum.NormalId.Bottom
		light.Range = 11 * MAP.scale
		light.Angle = 120
		light.Brightness = 2.5
		light.Color = HEAD.color
		light.Shadows = false
		light.Parent = head
	end
end

-- Signs: street names (blue, like Albanian street signs), STOP signs,
-- bus stop signs and the OpenStreetMap credit.
local SIGN_POST = { name = "SignPost", color = Color3.fromRGB(150, 152, 158), material = Enum.Material.Metal, collide = true, transparency = 0, reflectance = 0, shadow = true, folder = folder("Signs") }
local SIGN_KINDS = {
	street = { board = Color3.fromRGB(25, 70, 160), text = Color3.fromRGB(255, 255, 255), w = 2.6, h = 0.55, y = 2.6 },
	stop = { board = Color3.fromRGB(200, 20, 25), text = Color3.fromRGB(255, 255, 255), w = 0.8, h = 0.8, y = 2.1 },
	bus = { board = Color3.fromRGB(25, 70, 160), text = Color3.fromRGB(255, 255, 255), w = 0.7, h = 0.7, y = 2.4 },
	credit = { board = Color3.fromRGB(245, 245, 240), text = Color3.fromRGB(30, 30, 35), w = 4, h = 1, y = 2 },
}
local function signText(board, face, text, color)
	local gui = Instance.new("SurfaceGui")
	gui.Face = face
	gui.SizingMode = Enum.SurfaceGuiSizingMode.PixelsPerStud
	gui.PixelsPerStud = 40
	gui.Parent = board
	local label = Instance.new("TextLabel")
	label.Size = UDim2.fromScale(1, 1)
	label.BackgroundTransparency = 1
	label.TextColor3 = color
	label.Font = Enum.Font.GothamBold
	label.TextScaled = true
	label.Text = text
	label.Parent = gui
end
for _, s in ipairs(MAP.signs) do
	local kind = SIGN_KINDS[s[1]] or SIGN_KINDS.street
	local base = Vector3.new(s[2], 0, s[3])
	local top = (kind.y + kind.h / 2) * MAP.scale
	local post = Instance.new("Part")
	post.Size = Vector3.new(0.1 * MAP.scale, top, 0.1 * MAP.scale)
	post.CFrame = CFrame.new(base + Vector3.new(0, top / 2, 0))
	finish(post, SIGN_POST)
	local board = Instance.new("Part")
	board.Size = Vector3.new(kind.w * MAP.scale, kind.h * MAP.scale, 0.08 * MAP.scale)
	board.CFrame = CFrame.new(base + Vector3.new(0, kind.y * MAP.scale, 0)) * CFrame.Angles(0, math.rad(s[4]), 0)
	finish(board, { name = "Sign", color = kind.board, material = Enum.Material.SmoothPlastic, collide = false, transparency = 0, reflectance = 0, shadow = true, folder = SIGN_POST.folder })
	signText(board, Enum.NormalId.Front, s[5], kind.text)
	signText(board, Enum.NormalId.Back, s[5], kind.text)
end

-- Floating name labels for real shops, schools, the church, etc. They
-- only show up close by, so the map doesn't drown in text.
local LABEL_ANCHOR = { name = "Label", color = Color3.new(1, 1, 1), material = Enum.Material.SmoothPlastic, collide = false, transparency = 1, reflectance = 0, shadow = false, folder = folder("Labels") }
for _, l in ipairs(MAP.labels) do
	local anchor = Instance.new("Part")
	anchor.Size = Vector3.new(1, 1, 1)
	anchor.CFrame = CFrame.new(l[1], l[2], l[3])
	finish(anchor, LABEL_ANCHOR)
	local big = l[5] == 1
	local gui = Instance.new("BillboardGui")
	gui.Size = big and UDim2.new(0, 360, 0, 60) or UDim2.new(0, 240, 0, 34)
	gui.MaxDistance = big and 3000 or 180
	gui.AlwaysOnTop = big
	gui.Parent = anchor
	local label = Instance.new("TextLabel")
	label.Size = UDim2.fromScale(1, 1)
	label.BackgroundTransparency = 1
	label.TextColor3 = big and Color3.fromRGB(255, 225, 130) or Color3.fromRGB(255, 255, 255)
	label.TextStrokeTransparency = 0
	label.Font = Enum.Font.GothamBold
	label.TextScaled = true
	label.Text = l[4]
	label.Parent = gui
end

-- Grass under the whole area, tiled because a Part can't be bigger than
-- 2048 studs. Its top is at y = 0; roads sit just above it.
local GRASS = { name = "Ground", color = Color3.fromRGB(88, 118, 70), material = Enum.Material.Grass, collide = true, transparency = 0, reflectance = 0, shadow = false, folder = folder("Ground") }
local minX, maxX, minZ, maxZ = MAP.bounds[1] - 200, MAP.bounds[2] + 200, MAP.bounds[3] - 200, MAP.bounds[4] + 200
local TILE = 2000
for ix = 0, math.ceil((maxX - minX) / TILE) - 1 do
	for iz = 0, math.ceil((maxZ - minZ) / TILE) - 1 do
		local tile = Instance.new("Part")
		tile.Size = Vector3.new(TILE, 1, TILE)
		tile.CFrame = CFrame.new(minX + (ix + 0.5) * TILE, -0.5, minZ + (iz + 0.5) * TILE)
		finish(tile, GRASS)
	end
end

-- Where am I: the road lines go to every player (for the minimap), and
-- twice a second each player's current street and nearest real place are
-- worked out here and set as attributes the HUD shows.
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Players = game:GetService("Players")
local roadsValue = ReplicatedStorage:FindFirstChild("BabrruRoads") or Instance.new("StringValue")
roadsValue.Name = "BabrruRoads"
roadsValue.Value = MAP.roadlines
roadsValue.Parent = ReplicatedStorage

local lines = numbers(MAP.roadlines)
local places = {}
for _, l in ipairs(MAP.labels) do
	if l[5] == 0 then
		table.insert(places, l)
	end
end

local function distanceToSegment(px, pz, ax, az, bx, bz)
	local dx, dz = bx - ax, bz - az
	local lengthSq = dx * dx + dz * dz
	local t = 0
	if lengthSq > 0 then
		t = math.clamp(((px - ax) * dx + (pz - az) * dz) / lengthSq, 0, 1)
	end
	local cx, cz = ax + dx * t, az + dz * t
	return math.sqrt((px - cx) ^ 2 + (pz - cz) ^ 2)
end

task.spawn(function()
	while true do
		for _, player in ipairs(Players:GetPlayers()) do
			local character = player.Character
			local hrp = character and character:FindFirstChild("HumanoidRootPart")
			if hrp then
				local px, pz = hrp.Position.X, hrp.Position.Z
				local nearest, nearestD = 0, math.huge
				local named, namedD = 0, math.huge
				for i = 1, #lines, 6 do
					local d = distanceToSegment(px, pz, lines[i], lines[i + 1], lines[i + 2], lines[i + 3]) - lines[i + 4] / 2
					if d < nearestD then
						nearestD, nearest = d, lines[i + 5]
					end
					if lines[i + 5] > 0 and d < namedD then
						namedD, named = d, lines[i + 5]
					end
				end
				local street
				if nearestD > 30 * MAP.scale then
					street = named > 0 and ("near " .. MAP.streets[named]) or ""
				elseif nearest > 0 then
					street = MAP.streets[nearest]
				elseif named > 0 and namedD < 150 * MAP.scale then
					street = "Unnamed street, near " .. MAP.streets[named]
				else
					street = "Unnamed street"
				end
				local place, placeD = "", 70 * MAP.scale
				for _, l in ipairs(places) do
					local d = math.sqrt((l[1] - px) ^ 2 + (l[3] - pz) ^ 2)
					if d < placeD then
						placeD, place = d, l[4]
					end
				end
				player:SetAttribute("BabrruStreet", street)
				player:SetAttribute("BabrruPlace", place)
			end
		end
		task.wait(0.5)
	end
end)

if NIGHT_MODE then
	Lighting.ClockTime = 21
	Lighting.Brightness = 1
	Lighting.Ambient = Color3.fromRGB(40, 40, 55)
	Lighting.OutdoorAmbient = Color3.fromRGB(70, 70, 95)
	local bloom = Lighting:FindFirstChildOfClass("BloomEffect") or Instance.new("BloomEffect")
	bloom.Intensity = 0.9
	bloom.Size = 32
	bloom.Threshold = 0.85
	bloom.Parent = Lighting
	local color = Lighting:FindFirstChild("BabrruNightColor") or Instance.new("ColorCorrectionEffect")
	color.Name = "BabrruNightColor"
	color.Saturation = 0.15
	color.Contrast = 0.1
	color.Parent = Lighting
end

print(("[BabrruMap] Built Babrru from OpenStreetMap: %d parts (%s)."):format(built, MAP.summary))
